### ISSUE TITLE
Python is not installing

### ISSUE THREAD

**Issue by Atif1817** [RiSecID/parrot-in-termux#7]
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal python2 dh-python 2to3

E: Package 'python' has no installation candidate

**Comment by risecid** [comment]
you can use python3

To run programs that point to python, install the package python-is-python3:

apt install python-is-python3 or apt install python3

Or manually create a symlink to python3 (which basically is what the above package does):

sudo ln -s /usr/bin/python3 /usr/bin/python
